apiVersion: v1
kind: Namespace
metadata:
  name: qux
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: qux
spec:
  selector:
    matchLabels:
      app: server
  replicas: 3
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: "/etc/config"
      volumes:
      - name: config-volume
        configMap:
          name: server-conf